# Generated by Django 3.2 on 2021-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('emailID', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
